// shop_react+/src/pages/Cart.tsx
import React, { useState, useEffect } from 'react'; 
import { useDispatch, useSelector } from 'react-redux';
import { RootState } from '../store/store';
import { addItem, decrementItem, changeCurrency } from '../store/slices/cartSlice';
import { Product } from '../types/types';
import 'bootstrap/dist/css/bootstrap.min.css';
import { Currency } from '../types/types';

const Cart: React.FC = () => {
    const cartItems = useSelector((state: RootState) => state.cart.items) || [];
    const totalPrice = useSelector((state: RootState) => state.cart.totalPrice);
    const currency = useSelector((state: RootState) => state.cart.currency);
    const convertedTotal = useSelector((state: RootState) => state.cart.convertedTotal);
    const dispatch = useDispatch();

    const [contact, setContact] = useState({
        name: "",
        surname: "",
        address: "",
        phone: ""
    });

    const handleInputChange = (e: React.ChangeEvent<HTMLInputElement>) => {
        const { id, value } = e.target;
        setContact(prevState => ({
            ...prevState,
            [id]: value,
        }));
    };

    const handleCurrencyChange = (e: React.ChangeEvent<HTMLSelectElement>) => {
        const selectedCurrency = e.target.value as Currency;
        dispatch(changeCurrency(selectedCurrency));
    };

    const handleIncrement = (product: Product) => () => dispatch(addItem(product));
    
    const handleDecrement = (id: number) => () => dispatch(decrementItem(id));

    const handleOrder = () => {
        const order = {
            items: cartItems.map(item => ({
                id: item.id,
                title: item.title,
                image: item.image,
                description: item.description,
                price: item.price,
                quantity: item.quantity,
            })),
            total: convertedTotal,
            contacts: {
                name: contact.name,
                surname: contact.surname,
                address: contact.address,
                phone: contact.phone,
            },
            currency: currency
        };
        console.log('Order Summary:', JSON.stringify(order, null, 2));
    };

    return (
        <div className="container mt-4">
            {cartItems.length === 0 ? (
                <p className="text-center">Your cart is empty</p>
            ) : (
                <div className="row">
                    <div className="col-md-8">
                        <ul className="list-group">
                            {cartItems.map(item => (
                                <li key={item.id} className="list-group-item d-flex justify-content-between align-items-center">
                                    <div className="d-flex align-items-center">
                                        <img src={item.image} alt={item.title} className="img-thumbnail m-3" style={{ width: '100px' }} />
                                        <div className="ml-3">
                                            <h5>{item.title}</h5>
                                            <p>{item.description}</p>
                                            <p>${item.price}</p>
                                        </div>
                                    </div>
                                    <div className="d-flex align-items-center justify-content-center">
                                        <button style={{ width: '30px', height: '30px'}} className="btn btn-outline-secondary mx-2" onClick={handleDecrement(item.id)}>-</button>
                                        <span>{item.quantity}</span>
                                        <button style={{ width: '30px', height: '30px'}} className="btn btn-outline-secondary mx-2" onClick={handleIncrement(item)}>+</button>
                                    </div>
                                </li>
                            ))}
                        </ul>
                        <div className="mt-3 text-right">
                            <h4>TOTAL: {convertedTotal.toFixed(2)} {currency}</h4>
                        </div>
                    </div>
                    <div className="col-md-4">
                        <div className="card p-3">
                            <h5>Order Details</h5>
                            <form className="d-flex flex-column justify-content-center">
                                <div className="form-group">
                                    <label htmlFor="name">Name</label>
                                    <input type="text" className="form-control" id="name" onChange={handleInputChange} placeholder="Enter your name" />
                                </div>
                                <div className="form-group">
                                    <label htmlFor="surname">Surname</label>
                                    <input type="text" className="form-control" id="surname" onChange={handleInputChange} placeholder="Enter your surname" />
                                </div>
                                <div className="form-group">
                                    <label htmlFor="address">Address</label>
                                    <input type="text" className="form-control" id="address" onChange={handleInputChange} placeholder="Enter your address" />
                                </div>
                                <div className="form-group">
                                    <label htmlFor="phone">Phone</label>
                                    <input type="text" className="form-control" id="phone" onChange={handleInputChange} placeholder="Enter your phone number" />
                                </div>
                                <div className="form-group">
                                    <label htmlFor="currency">Currency</label>
                                    <select id="currency" className="form-control" value={currency} onChange={handleCurrencyChange}>
                                        <option value="USD">USD</option>
                                        <option value="UAH">UAH</option>
                                        <option value="GBP">GBP</option>
                                        <option value="JPY">JPY</option>
                                    </select>
                                </div>
                                <button type="button" className="btn btn-primary btn-block" onClick={handleOrder}>Order</button>
                            </form>
                        </div>
                    </div>
                </div>
            )}
        </div>
    );
};

export default Cart;

// shop_vue+/src/views/Cart.vue
<template>
    <div class="container mt-4">
        <div v-if="cartItems.length === 0" class="text-center">
            <p>Your cart is empty</p>
        </div>
        <div v-else class="row">
            <div class="col-md-8">
                <ul class="list-group">
                    <li v-for="item in cartItems" :key="item.id" class="list-group-item d-flex justify-content-between align-items-center">
                        <div class="d-flex align-items-center">
                            <img :src="item.image" :alt="item.title" class="img-thumbnail m-3" style="width: 100px;" />
                            <div class="ml-3">
                                <h5>{{ item.title }}</h5>
                                <p>{{ item.description }}</p>
                                <p>${{ item.price }}</p>
                            </div>
                        </div>
                        <div class="d-flex align-items-center justify-content-center">
                            <button style="width: 30px; height: 30px;" class="btn btn-outline-secondary mx-2" @click="handleDecrement(item.id)">-</button>
                            <span>{{ item.quantity }}</span>
                            <button style="width: 30px; height: 30px;" class="btn btn-outline-secondary mx-2" @click="handleIncrement(item)">+</button>
                        </div>
                    </li>
                </ul>
                <div class="mt-3 text-right">
                    <h4>TOTAL: {{ convertedTotal.toFixed(2) }} {{ currency }}</h4>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card p-3">
                    <h5>Order Details</h5>
                    <form class="d-flex flex-column justify-content-center">
                        <div class="form-group">
                            <label for="name">Name</label>
                            <input type="text" class="form-control" id="name" v-model="contact.name" placeholder="Enter your name" />
                        </div>
                        <div class="form-group">
                            <label for="surname">Surname</label>
                            <input type="text" class="form-control" id="surname" v-model="contact.surname" placeholder="Enter your surname" />
                        </div>
                        <div class="form-group">
                            <label for="address">Address</label>
                            <input type="text" class="form-control" id="address" v-model="contact.address" placeholder="Enter your address" />
                        </div>
                        <div class="form-group">
                            <label for="phone">Phone</label>
                            <input type="text" class="form-control" id="phone" v-model="contact.phone" placeholder="Enter your phone number" />
                        </div>
                        <div class="form-group">
                            <label for="currency">Currency</label>
                            <select id="currency" class="form-control" v-model="selectedCurrency" @change="handleCurrencyChange">
                                <option value="USD">USD</option>
                                <option value="UAH">UAH</option>
                                <option value="GBP">GBP</option>
                                <option value="JPY">JPY</option>
                            </select>
                        </div>
                        <button type="button" class="btn btn-primary btn-block" @click="handleOrder">Order</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</template>

<script lang="ts">
import { defineComponent, ref, computed } from 'vue';
import { useStore } from 'vuex';
import { Product, Currency } from '../types/types';

interface Contact {
    name: string;
    surname: string;
    address: string;
    phone: string;
}

export default defineComponent({
    name: 'Cart',
    setup() {
        const store = useStore();
        const contact = ref<Contact>({
            name: "",
            surname: "",
            address: "",
            phone: ""
        });
        
        const selectedCurrency = ref<Currency>(store.getters.currency);
        const cartItems = computed(() => store.getters.cartItems);
        const convertedTotal = computed(() => store.getters.convertedTotal);
        const currency = computed(() => store.getters.currency);

        const handleIncrement = (product: Product) => {
            store.dispatch('addItem', product);
        };

        const handleDecrement = (id: number) => {
            store.dispatch('decrementItem', id);
        };

        const handleCurrencyChange = () => {
            store.dispatch('changeCurrency', selectedCurrency.value);
        };

        const handleOrder = () => {
            const order = {
                items: cartItems.value.map((item: any) => ({
                    id: item.id,
                    title: item.title,
                    image: item.image,
                    description: item.description,
                    price: item.price,
                    quantity: item.quantity,
                })),
                total: convertedTotal.value,
                contacts: {
                    name: contact.value.name,
                    surname: contact.value.surname,
                    address: contact.value.address,
                    phone: contact.value.phone,
                },
                currency: currency.value
            };
            console.log('Order Summary:', JSON.stringify(order, null, 2));
        };

        return {
            cartItems,
            convertedTotal,
            currency,
            contact,
            selectedCurrency,
            handleIncrement,
            handleDecrement,
            handleCurrencyChange,
            handleOrder
        };
    }
});
</script>
