// shop_react+/src/pages/Home.tsx
import { useState, useEffect } from 'react';
import { Product } from '../types/types';
import ProductList from '../components/ProductList';


const Home: React.FC<{}> = () => {
    const [products, setProducts] = useState<Product[]>([]);

    async function fetchListOfProducts() {
        const res = await fetch('https://fakestoreapi.com/products');
        const data = await res.json()
        if (data) {
            setProducts(data)
        }
      }
      
      useEffect(() => {
          fetchListOfProducts()
      }, [])
      
      
      return (
        <div className="container mt-5">
            <ProductList products={products}></ProductList>
        </div>
      );
}

export default Home;

// shop_vue+/src/views/Home.vue
<template>
    <div class="container mt-5">
        <ProductList :products="products" />
    </div>
</template>

<script lang="ts">
import { defineComponent, ref, onMounted } from 'vue';
import ProductList from '../components/ProductList.vue';
import { Product } from '../types/types';

export default defineComponent({
    name: 'Home',
    components: {
        ProductList
    },
    setup() {
        const products = ref<Product[]>([]);

        const fetchListOfProducts = async () => {
            const res = await fetch('https://fakestoreapi.com/products');
            const data = await res.json();
            if (data) {
                products.value = data;
            }
        };

        onMounted(() => {
            fetchListOfProducts();
        });

        return {
            products
        };
    }
});
</script>
