// shopping-cart_+/src/pages/home.jsx
import { useEffect, useState } from "react"
import ProductTile from "../components/product-tile";

export default function Home() {
    const [products, setProducts] = useState([])
    const [loading, setLoading] = useState(false)

    async function fetchListOfProducts() {
        setLoading(true)
        const res = await fetch('https://fakestoreapi.com/products');
        const data = await res.json()
        if (data) {
            setLoading(false)
            setProducts(data)
        }
   }

    useEffect(() => {
        fetchListOfProducts()
    }, [])

    return (
        <div>
          {loading ? (
            <div className="min-h-screen w-full">
              ...Loading
            </div>
          ) : (
            <div className="min-h-[80vh] grid sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4">
              {products && products.length ? (
                products.map((productItem) => (
                  <ProductTile key={productItem.id} product={productItem} />
                ))
              ) : null}
            </div>
          )}
        </div>
      );   
}

// shop_vue+/src/views/Home.vue
<template>
    <div class="container mt-5">
        <ProductList :products="products" />
    </div>
</template>

<script lang="ts">
import { defineComponent, ref, onMounted } from 'vue';
import ProductList from '../components/ProductList.vue';
import { Product } from '../types/types';

export default defineComponent({
    name: 'Home',
    components: {
        ProductList
    },
    setup() {
        const products = ref<Product[]>([]);

        const fetchListOfProducts = async () => {
            const res = await fetch('https://fakestoreapi.com/products');
            const data = await res.json();
            if (data) {
                products.value = data;
            }
        };

        onMounted(() => {
            fetchListOfProducts();
        });

        return {
            products
        };
    }
});
</script>
